language: go
go:
  - 1.3
  - tip
sudo: required
install:
  - go get 'github.com/carbocation/interpose'
  - go get 'github.com/codegangsta/negroni'
  - go get 'github.com/codegangsta/inject'
  - go get 'github.com/fiatjaf/sublevel'
  - go get 'github.com/go-martini/martini'
  - go get 'github.com/golang/snappy'
  - go get 'github.com/gorilla/context'
  - go get 'github.com/gorilla/mux'
  - go get 'github.com/franela/goblin'
  - go get 'github.com/meatballhat/negroni-logrus'
  - go get 'github.com/docopt/docopt-go'
  - go get 'gopkg.in/tylerb/graceful.v1'
  - go get 'github.com/onsi/gomega'
  - go get 'github.com/rs/cors'
  - go get 'github.com/syndtr/goleveldb/leveldb'
  - go get 'github.com/Sirupsen/logrus'
  - go get
  - export GOPATH=$HOME/gopath
  - export PATH=$PATH:$GOPATH/bin
  - cd integration_tests/ && npm install && cd -
env:
  - ENVIRONMENT=production SUMMADB_ADDRESS=http://0.0.0.0:5000/subdb
before_script:
  - start-stop-daemon --start --quiet --pidfile /tmp/summadb.pid --make-pidfile --background --startas "$GOPATH/bin/summadb --reset"
script: cd database/test/ && go test && cd - && cd handle/test/ && go test && cd - && cd integration_tests && npm test && cd -
