language: go
go:
  - 1.3
  - tip
sudo: false
install:
  - go get 'github.com/carbocation/interpose'
  - go get 'github.com/codegangsta/negroni'
  - go get 'github.com/codegangsta/inject'
  - go get 'github.com/fiatjaf/sublevel'
  - go get 'github.com/go-martini/martini'
  - go get 'github.com/golang/snappy'
  - go get 'github.com/gorilla/context'
  - go get 'github.com/gorilla/mux'
  - go get 'github.com/franela/goblin'
  - go get 'github.com/meatballhat/negroni-logrus'
  - go get 'github.com/docopt/docopt-go'
  - go get 'gopkg.in/tylerb/graceful.v1'
  - go get 'github.com/onsi/gomega'
  - go get 'github.com/rs/cors'
  - go get 'github.com/syndtr/goleveldb/leveldb'
  - go get 'github.com/Sirupsen/logrus'
  - go get
  - export GOPATH=$HOME/gopath
  - export PATH=$PATH:$GOPATH/bin
  - . $HOME/.nvm/nvm.sh
  - nvm install 4.2
  - nvm use 4.2
  - cd integration_tests/ && npm install && cd -
env:
  - ENVIRONMENT=production SUMMADB_ADDRESS=http://0.0.0.0:5000/subdb SECOND_SUMMADB_ADDRESS=http://0.0.0.0:5001
before_script:
  - start-stop-daemon -S --pidfile /tmp/summa1.pid --make-pidfile --background --startas $GOPATH/bin/summadb -- --reset --port 5000 --db /tmp/db1
  - start-stop-daemon -S --pidfile /tmp/summa2.pid --make-pidfile --background --startas $GOPATH/bin/summadb -- --reset --port 5001 --db /tmp/db2
  - nodejs --version
script: cd database/test/ && go test && cd - && cd handle/test/ && go test && cd - && cd integration_tests && npm test && cd -
